### ISSUE TITLE
instructions in the readme reference files which don't exist

### ISSUE THREAD

**Issue by MarcSchunk** [petergtz/1-click-bosh-lite-pipeline#9]
Instructions in the readme reference two files which don't exist:
```
 change-to-single-dynamic-network-named-default.yml \
 change-cloud-provider-mbus-host.yml \
```

Are these files needed? They exist on a branch. Does the branch need merging?

**Comment by petergtz** [comment]
Hi @MarcSchunk,

I just fixed this in https://github.com/petergtz/1-click-bosh-lite-pipeline/commit/2a03492e67c8ac0e9619506cdcfaaaeff1f59bec

Could you please try again?

**Comment by MarcSchunk** [comment]
works now - thx
